add linux-emulator 3.12 kernel from tizen.org
This is the kernel with yagl support which is needed to have
hardware accelerated graphics when running under a suitable qemu.

It is a known issue that the ramfs build causes QA warnings:

ERROR: QA Issue: File '/usr/src/kernel/ramfs/busybox' from linux-emulator was already stripped, this will prevent future debugging! [already-stripped]
ERROR: QA Issue: non debug package contains .debug directory: kernel-dev path /work/qemux86-poky-linux/linux-emulator/3.10+gitAUTOINC+38ecc4894a-r1/packages-split/kernel-dev/usr/src/kernel/ramfs/.debug/v86d [debug-files]

Perhaps disable ramdisk support entirely?